# Generated by Django 5.2.8 on 2025-11-11 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父部门ID')),
                ('ancestors', models.CharField(default='', max_length=50, verbose_name='祖级列表')),
                ('dept_name', models.CharField(max_length=30, verbose_name='部门名称')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('leader', models.CharField(blank=True, max_length=20, verbose_name='负责人')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='部门状态')),
                ('create_by', models.CharField(blank=True, max_length=64, verbose_name='创建者')),
                ('update_by', models.CharField(blank=True, max_length=64, verbose_name='更新者')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'sys_dept',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='create_by',
            field=models.CharField(blank=True, max_length=64, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time'),
        ),
        migrations.AddField(
            model_name='user',
            name='dept_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Department ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_by',
            field=models.CharField(blank=True, max_length=64, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Time'),
        ),
    ]
